"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TOGGLE_TAG_IN_CELL = "CORE/TOGGLE_TAG_IN_CELL";
exports.SET_IN_CELL = "SET_IN_CELL";
exports.MOVE_CELL = "MOVE_CELL";
exports.DELETE_CELL = "DELETE_CELL";
exports.CREATE_CELL_BELOW = "CREATE_CELL_BELOW";
exports.CREATE_CELL_ABOVE = "CREATE_CELL_ABOVE";
// Deprecation Warning: This action type is being deprecated. Please use DELETE_CELL instead
exports.REMOVE_CELL = "REMOVE_CELL";
// DEPRECATION WARNING: This action type is being deprecated. Please use CREATE_CELL_BELOW instead
exports.CREATE_CELL_AFTER = "CREATE_CELL_AFTER";
// DEPRECATION WARNING: This action type is being deprecated. Please use CREATE_CELL_ABOVE instead
exports.CREATE_CELL_BEFORE = "CREATE_CELL_BEFORE";
exports.CREATE_CELL_APPEND = "CREATE_CELL_APPEND";
exports.UNHIDE_ALL = "UNHIDE_ALL";
exports.TOGGLE_CELL_OUTPUT_VISIBILITY = "TOGGLE_CELL_OUTPUT_VISIBILITY";
exports.TOGGLE_CELL_INPUT_VISIBILITY = "TOGGLE_CELL_INPUT_VISIBILITY";
exports.CLEAR_OUTPUTS = "CLEAR_OUTPUTS";
exports.CLEAR_ALL_OUTPUTS = "CLEAR_ALL_OUTPUTS";
exports.FOCUS_CELL = "FOCUS_CELL";
exports.FOCUS_NEXT_CELL = "FOCUS_NEXT_CELL";
exports.FOCUS_PREVIOUS_CELL = "FOCUS_PREVIOUS_CELL";
exports.FOCUS_CELL_EDITOR = "FOCUS_CELL_EDITOR";
exports.FOCUS_NEXT_CELL_EDITOR = "FOCUS_NEXT_CELL_EDITOR";
exports.FOCUS_PREVIOUS_CELL_EDITOR = "FOCUS_PREVIOUS_CELL_EDITOR";
exports.CUT_CELL = "CUT_CELL";
exports.COPY_CELL = "COPY_CELL";
exports.PASTE_CELL = "PASTE_CELL";
exports.CHANGE_CELL_TYPE = "CHANGE_CELL_TYPE";
exports.UPDATE_CELL_STATUS = "UPDATE_CELL_STATUS";
exports.UPDATE_OUTPUT_METADATA = "UPDATE_OUTPUT_METADATA";
