"use strict";
/**
 * @module actions
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PUBLISH_TO_BOOKSTORE = "CORE/PUBLISH_TO_BOOKSTORE";
exports.PUBLISH_TO_BOOKSTORE_AFTER_SAVE = "CORE/PUBLISH_TO_BOOKSTORE_AFTER_SAVE";
exports.PUBLISH_TO_BOOKSTORE_SUCCEEDED = "CORE/PUBLISH_TO_BOOKSTORE_SUCCEEDED";
exports.PUBLISH_TO_BOOKSTORE_FAILED = "CORE/PUBLISH_TO_BOOKSTORE_FAILED";
